### ISSUE TITLE
How to install on macOS Blender 9.3?

### ISSUE THREAD

**Issue by CS6** [BlenderNPR/BEER#137]
I try to download the latest release and go to the plug-in menu to install，However, the following error will appear. Is there any other way I can use besides switching to the portable version of windows Blender?

Device: 
MacBook Pro (15-inch, 2018)

Version:
macOS 11.3.1 Blender 9.3

![image](https://user-images.githubusercontent.com/16307922/134765896-c654e9ff-4739-475a-94f3-62a9ac05dd3f.png)

**Comment by pragma37** [comment]
Hello! This was a known issue. (#19)
It was supposedly solved on the latest Python versions, so I recently removed the fix.
I reverted the changes, so it should work again.

Keep in mind that the MacOS version is the only one that I can't test myself and that (due to driver limits) only the most basic Malt features are supported.
