### ISSUE TITLE
Malt crash loop upon selection

### ISSUE THREAD

**Issue by pixelemy** [BlenderNPR/BEER#144]
Issue:
- Malt opens and closes intermittently upon activation

Reproduction steps:
1. Switch to render properties tab.
2. Change render engine from whatever it is to **Malt**.
3. Anomaly ensues.

Video demo:
https://cdn.discordapp.com/attachments/729127664434282557/894316225805553674/malt-issue-win7-sp1-blender-v2.83.16-malt-latest-release.mp4

Console Screenshot:
https://media.discordapp.net/attachments/729127664434282557/894533426852544522/unknown.png?width=453&height=676

Session log + .blend files:
[malt-bug-report-files.zip](https://github.com/bnpr/Malt/files/7282101/malt-bug-report-files.zip)

Environment:
Screen reso: 1080p
win 7 sp1
blender v2.83.16
malt: latest release
- https://github.com/bnpr/Malt/releases/tag/Release-latest
- 4003c51
- Jul 18, 2021 11:45PM GMT+8

P.S.
Also tested with development-latest (Oct. 03, 2021 version), issue still present.

**Comment by pragma37** [comment]
Hi! Thanks for the detailed report.

Your card is reporting a GL_OUT_OF_MEMORY error.
This usually indicates it's running out of VRAM, but in this case, since it's failing at startup when compiling the Default Shader (after compiling other simpler shaders) I guess the Default Shader has too many instructions or uses too many resources for your card.

You could try updating your graphics driver, just in case, but an Intel HD 4400 GPU might just not be enough to run the default Malt pipeline.

You can try to run this [test pipeline](https://github.com/bnpr/Malt/files/6976528/minipipeline.benchmark.zip), just to make sure if that's indeed the issue.

**Comment by pixelemy** [comment]
Thanks for the initial assessment.

I've run the test pipeline file. I ran it twice. It's working fine.
I also haven't updated my gfx driver yet, when I ran the file.

Vid demo:
https://user-images.githubusercontent.com/60591594/136108222-f7ec38da-ff76-4e9d-8a59-65cb59ac1894.mp4

Session log files + console ss:
[malt-test-pipeline-files.zip](https://github.com/bnpr/Malt/files/7289542/malt-test-pipeline-files.zip)

**Comment by infrank** [comment]
I have the same problem. I cannot get it running. These are my specs:

- Windows 7  
- NVIDIA 980 Ti (Updated latest drivers)
- same Malt latest release version
- Blender 2.93.5 LTS

A screenshot of the console:

![image](https://user-images.githubusercontent.com/83601498/141034128-1958459d-d22c-4223-a9f8-32f847dd1fa9.png)

**Comment by pragma37** [comment]
@infrank 
I doubt your issue is related even if the symptoms are the same. Please, open a new issue with the required info:
https://github.com/bnpr/Malt#bug-reports
