### ISSUE TITLE
RX480 8G: Unable to load numpy_formathandler accelerator from OpenGL_accelerate

### ISSUE THREAD

**Issue by Schofje** [BlenderNPR/BEER#227]
### Malt version

Latest release as of time of writing

### Blender version

3.0.1

### OS

Windows 10 Pro

### Hardware info

i5 6400 | RX480 8G | 32GB DDR4 RAM

### Issue description and reproduction steps

Opening up MALT causes this.
No more no less. Viewport still allows basic object transformation but is slow.

Screen is gray, world is not rendering
![Screenshot 2022-01-29 203326](https://user-images.githubusercontent.com/49023943/151675018-e83c21ae-ac4b-46de-87ee-806443aa6db8.png)

### Attachments

[malt 2022-01-29(20-27).log](https://github.com/bnpr/Malt/files/7964416/malt.2022-01-29.20-27.log)

**Comment by pragma37** [comment]
Hi! Thank you for the report.
I can reproduce the error on my AMD laptop, but not on my Nvidia desktop.
The error is caused by the library that Malt uses for calling OpenGL functions.

I've been looking into it but I haven't found a solution yet.
I've opened a report on the PyOpenGL Github to see if they can help.

**Comment by pragma37** [comment]
This one took me a bit to figure out, but I think it should be fixed now.
Could you download the latest version and tell me if it works for you?

**Comment by Schofje** [comment]
It works for me! I am glad I can now run it :) I just have to learn how to use malt and glsl now whahahaha
