### ISSUE TITLE
Parameters from custom pipelines only appear when their name starts with "Ba"

### ISSUE THREAD

**Issue by panthavma** [BlenderNPR/BEER#280]
### Malt version

Development

### Blender version

3.1.0

### OS

Ubuntu 20.04.3 LTS

### Hardware info

Intel Xeon E3-1200 | ?? RAM | NVidia GTX 1080

### Issue description and reproduction steps

Parameters from custom pipelines don't appear except in the world tab when starting with "Ba".

The example here has 4 variables:
- Parameter 1 (not shown, not used)
- Parameter 2 (not shown, used)
- Barameter 3 (shown, not used)
- Background Test (shown, not used)

### Attachments

[TestPipeline.zip](https://github.com/bnpr/Malt/files/8391124/TestPipeline.zip)

**Comment by pragma37** [comment]
The UI rendering is failing because your default material is using the nodes from the NPR_Pipeline.
Parameters are drawn in alphabetic order so anything after "Material" was not being drawn.

I should find a good way to handle this, but for now just make sure that there aren't node groups from other pipelines used in your scene:
![imagen](https://user-images.githubusercontent.com/36610999/161106471-3ae04d35-e168-4be3-8283-ff6650babd3e.png)

![imagen](https://user-images.githubusercontent.com/36610999/161107096-a631b78f-1686-4d4c-93e9-a071c86029b5.png)

**Comment by panthavma** [comment]
Ooooh okay, I see. Thanks for the answer!
