### ISSUE TITLE
Rendering failure, grey viewport objects

### ISSUE THREAD

**Issue by io7m** [BlenderNPR/BEER#367]
### Malt version

1.0.0.beta.2.Release

### Blender version

3.2.1

### OS

Linux x86_64

### Hardware info

AMD Ryzen 5 3600|32gb RAM|Radeon RX 5700

### Issue description and reproduction steps

Starting up Malt results in all of the viewport objects being rendered in flat grey tone, and moving objects around is pretty slow (presumably due to the repeated exceptions being raised in the background).

I'm on plain Arch Linux with Xorg setup, so this message in the log file might be suspicious:

```
glfw.GLFWError: (65544) b'Wayland: Failed to connect to display'
```

There shouldn't be any Wayland involved.

### Attachments

[malt-0.log](https://github.com/bnpr/Malt/files/9213765/malt-0.log)

**Comment by pragma37** [comment]
I guess this is a distro incompatibility, the Linux binaries are built in Ubuntu.

You can try to build the binaries yourself:
https://github.com/bnpr/Malt/blob/Development/docs/Setup-BlenderMalt-for-Development.md

To get the zipped addon, instead of:
`<Blender Python Path> <Cloned Repo Path>/scripts/setup_blender_addon.py --scripts-folder <User Scripts Path>`
run:
`<Blender Python Path> <Cloned Repo Path>/scripts/setup_blender_addon.py --copy-modules`

**Comment by io7m** [comment]
Sorry, I missed your response to this. I'll try building this shortly!

**Comment by io7m** [comment]
Building it locally made no difference, sadly.

[malt 2022-08-11(17-38).log](https://github.com/bnpr/Malt/files/9310729/malt.2022-08-11.17-38.log)

**Comment by pragma37** [comment]
Sorry, this is not something I can really fix directly from the Malt side.

Seems like the Python wrapper recently made an update related to Wayland support, it may have broken something.
The latest stable Malt Release is older than that update, so I would try it first if you're using the Development version.
https://github.com/bnpr/Malt/releases/tag/Release-latest

Otherwise, you can try to delete the GLFW libraries from the python package:
`BlenderMalt-Linux.zip\BlenderMalt\.MaltPath\Malt\.Dependencies-310\glfw\wayland`
`BlenderMalt-Linux.zip\BlenderMalt\.MaltPath\Malt\.Dependencies-310\glfw\x11`

And install glfw directly from your distro package manager.

**Comment by io7m** [comment]
Wow, I've just discovered that this was my fault...

```
$ pacman -Q | grep glfw
glfw-wayland 3.3.8-1

$ sudo pacman -S glfw-x11
resolving dependencies...
looking for conflicting packages...
:: glfw-x11 and glfw-wayland are in conflict (glfw). Remove glfw-wayland? [y/N] y

Packages (2) glfw-wayland-3.3.8-1 [removal]  glfw-x11-3.3.8-1

Total Download Size:   0.11 MiB
Total Installed Size:  0.50 MiB
Net Upgrade Size:      0.02 MiB

:: Proceed with installation? [Y/n] Y
:: Retrieving packages...
 glfw-x11-3.3.8-1-x86_64                                 110.9 KiB   431 KiB/s 00:00 [#################################################] 100%
(1/1) checking keys in keyring                                                       [#################################################] 100%
(1/1) checking package integrity                                                     [#################################################] 100%
(1/1) loading package files                                                          [#################################################] 100%
(1/1) checking for file conflicts                                                    [#################################################] 100%
(2/2) checking available disk space                                                  [#################################################] 100%
:: Processing package changes...
(1/1) removing glfw-wayland                                                          [#################################################] 100%
(1/1) installing glfw-x11                                                            [#################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
```

![working](https://user-images.githubusercontent.com/612494/184216242-d1df33c2-af93-4352-b982-d5afd4b67896.png)

Sorry for the noise. I've no idea how/why the wayland variant of `glfw` managed to get itself installed.
