### ISSUE TITLE
Windows Security detects trojan when downloading BlenderMalt

### ISSUE THREAD

**Issue by deastman2** [BlenderNPR/BEER#38]
I just attempted to download BlenderMalt for Windows, using the Chrome browser on Windows 10.  The download fails, and Windows Security reports that BelnderMalt contains "Trojan:Win32/Tisifi.B".

**Comment by BlenderNPR** [comment]
No issue on my scan. 
On windows and on Virus Total
https://www.virustotal.com/gui/file/bb4867b927cd5280d922853398706bc8197de02420e44c25f5f07ff8742bbd45/detection

**Comment by deastman2** [comment]
![VirusDetected](https://user-images.githubusercontent.com/66821776/103476857-29535300-4d6e-11eb-93fc-a691ddadf88d.jpg)

I just tested again, with the same results.  See attached screen capture.

**Comment by bjorn3** [comment]
If you search for "windows defender Trojan:Win32/Tisifi.B", you will find all kinds of programs being detected as this. This includes sublime text at one point. Because of this, I am pretty sure this is a heuristic and not detecting a specific piece of malware. This will probably go away once more people start to use it and the reputation of the executables increases as a result.

**Comment by deastman2** [comment]
Okay, thank you for looking into that.  I'll consider the issue closed.

**Comment by pragma37** [comment]
I updated the build script to remove the bin folder.
That's the folder where PIP places command line utilites.
Since we don't use those and small executables usually trigger false positives, we can just avoid the hassle.
