### ISSUE TITLE
Flipbook Iterating in the Wrong Order

### ISSUE THREAD

**Issue by bardificer** [BlenderNPR/BEER#410]
### Malt version

node-groups-latest (9.29.2022)

### Blender version

Blender 3.3

### OS

EndeavourOs (5.19.12-zen kernel)

### Hardware info

AMD R5-5625U | 16GB RAM | Integrated Vega Graphics

### Issue description and reproduction steps

Flipbook node reads in incorrect order. In the image attached (used in testing), the flipbook node reads it from page 0->8 as 7,8,9,4,5,6,1,2,3 instead of 1,2,3,4,5,6,7,8,9.

This is mostly to verify with the original creator that this is not intended functionality. Standard spritesheets/flipbooks usually do not read in this order. If this is a bug and not intended functionality, I can pull request with my fix for it.

### Attachments

![3x3Test](https://user-images.githubusercontent.com/39376345/193187525-b390cd62-2b8f-4cc6-a49b-cc442b6bee4c.png)

**Comment by pragma37** [comment]
I think starting at the top left would be, indeed, the correct behavior.
Do you agree @Kolupsy ?

**Comment by Kolupsy** [comment]
I think the order is pretty arbitrary. The reason why it is currently going from left to right and bottom to top is because this is the most straight-forward way of converting UV into the flipbook grid. There is probably a convention or a most commonly used order for flipbook textures but they would they would require reordering of the UV space.
I think the best solution would be to use an enum to switch the 'scanning order' of the  flipbook texture

edit: so technically this is intended behavior because I have only used flipbook textures that have their sprites arranged in a way where the malt node samples them in the correct order but I have not really thought about potential conflicts with other arrangement methods. I guess arranging them like latin writing makes sense...

**Comment by pragma37** [comment]
Yep, I get why you did it that way since it's what makes the most sense in OpenGL coordinates.

On the other hand, I made a quick survey of existing apps to generate flipbook textures, and literally all of them start from the top left:
https://realtimevfx.com/t/i-created-a-tool-that-creates-flipbooks-for-you/11160
https://jangafx.com/software/embergen/

We can put an enum, since if you are generating the flipbooks in Malt itself it could be easier to work with, but I think the default should be as @Bardificer suggests.

**Comment by bardificer** [comment]
Okay. I'll make a pull request with the fix, and I can look into how to make it a choice for the users.

**Comment by pragma37** [comment]
For adding an enum in the UI you can do it like this:

```glsl
/* META
    @tex: label=Texture;
    @uv: label=UV; default=UV[0];
    @page: min=0.0;
    @origin: subtype=ENUM(Top Left,Bottom Left);
*/
vec4 Flipbook(sampler2D tex, vec2 uv, ivec2 dimensions, float page, int origin)
{   
    bool is_top_left = origin == 0;
    
    int f = int(floor(page));
    float frac = fract(page);
    vec4 c = sample_flipbook(tex, uv, dimensions, f, is_top_left);
    if(frac == 0.0)
    {
        return c;
    }
    return mix(
        c,
        sample_flipbook(tex, uv, dimensions, f + 1, is_top_left),
        fract(page)
    );
}
```
