### ISSUE TITLE
RGB Curves in Geo Nodes breaks Vertex Colors

### ISSUE THREAD

**Issue by dibli-goost** [BlenderNPR/BEER#441]
### Malt version

Node Groups

### Blender version

Blender 3.3

### OS

Windows 10

### Hardware info

AMD Ryzen Threadripper 1920x 12-Core Processor, 3950 Mhz, 24 Logical Processors | 32GB RAM | Radeon RX 570 Series

### Issue description and reproduction steps

When transferring Vertex Color Attributes out of Geo Nodes and into Malt, if a RGB Curves is linked in the node tree, it will break any Color Attribute it is connected to.

![image](https://user-images.githubusercontent.com/31767887/200438382-f8f0e402-8631-43e3-9c53-ca8dec3601fb.png)

Sometimes it also seems to create this faceted look, but I'm not really sure why it's not happening in the attached blend.

![image](https://user-images.githubusercontent.com/31767887/200439427-c362249d-b432-4e3e-8175-45a08afba758.png)

![image](https://user-images.githubusercontent.com/31767887/200439370-6edd4554-fb3d-471d-a769-68e4c4dd356d.png)

I did test in EEVEE too, and it does seem to work there just fine. 

### Attachments

[Geometry Nodes RGB Curves Bug.zip](https://github.com/bnpr/Malt/files/9956334/Geometry.Nodes.RGB.Curves.Bug.zip)

**Comment by pragma37** [comment]
It seems like the RGB Curves node sets the alpha to 0.
![imagen](https://user-images.githubusercontent.com/36610999/200875449-2bf3be30-2e1f-4341-bab5-d74800fe4708.png)
![imagen](https://user-images.githubusercontent.com/36610999/200876043-15ae056b-43f0-4ab7-95a4-157e3f538f47.png)

I guess EEVEE doesn't read the alpha value from Vertex Colors, so Geometry Nodes ignore the alpha value.
Vertex colors alpha is kind of weird in Blender because they're there but AFAIK they're not really used anywhere.

In any case, this is not really an error on the Malt side. And I don't think we should ignore the vertex color alpha to "fix" it.
