### ISSUE TITLE
Render not working

### ISSUE THREAD

**Issue by Gero39** [BlenderNPR/BEER#516]
### Malt version

Release-latest

### Blender version

Blender 3.6.1

### OS

Windows 10 

### Hardware info

Intel i3-7100U | 12 gb ram | Nvidia Geforce 940mx (2gb)

### Issue description and reproduction steps

In a standard cube project with Malt Default Mesh, the cube has a background color without any lighting.
![malt](https://github.com/bnpr/Malt/assets/75932124/1cedd8b4-672c-4331-84aa-5ea48e20bdfa)

### Attachments

[malt 2023-08-06(15-54).log](https://github.com/bnpr/Malt/files/12269679/malt.2023-08-06.15-54.log)
[malt-test.zip](https://github.com/bnpr/Malt/files/12269683/malt-test.zip)

**Comment by pragma37** [comment]
The log shows this error (and others related to this):
> Unable to import OpenGL.arrays.numpymodule.NumpyHandler: No numpy module present: cannot import name 'lib' from partially initialized module 'numpy' (most likely due to a circular import) (C:\Users\Egor\AppData\Roaming\Python\Python310\site-packages\numpy\__init__.py)

It looks like instead of using the `numpy` library that comes bundled with Blender, Python is trying to import it from your global Python installation, which shouldn't happen. Not sure what could be the cause.

 I would download the portable (zip) version of Blender and add a local config folder, like this:

![imagen](https://github.com/bnpr/Malt/assets/36610999/19ce6f01-19ea-44b4-962c-cfb1ad56ef8f)

This will make this Blender installation completely isolated from your main one, so you can ensure there are no other addons or user settings interfering.
Then try to install BlenderMalt on this Blender installation.
If the issue persists, it must be an issue with your Windows environment variables.

**Comment by Gero39** [comment]
After removing the local numpy everything worked, thanks!
