### ISSUE TITLE
Crash when execute `node.add_search` in Malt Node Tree

### ISSUE THREAD

**Issue by yozba** [BlenderNPR/BEER#518]
### Malt version

Release

### Blender version

Blender 3.6.0 or more

### OS

Windows 10 64bits

### Hardware info

Intel i9-10900K | 64GB RAM | Nvidia RTX 3070 8GB

### Issue description and reproduction steps

Blender instantly crashes when executing `node.add_search` in Malt node tree. Press Shift+A and then click "Search... " to test.
I tested after loading factory settings, so I think this is not because of any other addons I installed.
This doesn't happen until Blender 3.5.1, so might be something changed in Blender 3.6.

### Attachments

[malt 2023-09-03(05-52).log](https://github.com/bnpr/Malt/files/12504713/malt.2023-09-03.05-52.log)

**Comment by pragma37** [comment]
I have to look deeper into it, but I don't think this is something I can fix on the Malt side.
So a fix may need to wait for a future 3.6 release or even 4.0. 🙁

The Malt version of search is much better (not only because it doesn't crash Blender 😅),  so you should use that instead.

![imagen](https://github.com/bnpr/Malt/assets/36610999/3115b011-a7f8-4840-9c23-e921b761d274)

But yeah... it's not great to have it near an auto-destruction button.

**Comment by yozba** [comment]
Oh, I see. I'm sorry I'm not much famililar with programming, so I can't help much. 😥

**Comment by yozba** [comment]
As you may know, I confirm that `wm.search_single_menu(menu_idname="NODE_MT_add")` doesn't cause crash in Blender 4.0.
There is no more `node.add_search` command. so, this bug causes in only 3.6.x.

**Comment by pragma37** [comment]
Thank you for the reminder.
Closing then.
